### ISSUE TITLE
is this still being maintained?

### ISSUE THREAD

**Issue by gmaliar** [apigy/selfstarter#117]

**Comment by Drefresh** [comment]
short answer is no. its not.

**Comment by gmaliar** [comment]
@Drefresh are you part of Lockitron organization? Can you give us merge rights so we can keep maintaining this project?

**Comment by pgerhardt** [comment]
Lockitron still has a vested interest in this project but it is not currently in a deployable state. If you want to get it up to speed, make a fork and if it looks good we can link to it in the readme.md
