### ISSUE TITLE
We're sorry, but something went wrong (500)

### ISSUE THREAD

**Issue by talhof8** [apigy/selfstarter#12]
Hey!
I've tried deploying selfstarter via Heroku. I keep getting the 500 error. I tried 3 different accounts and various ways of installation.  I'm new to Heroku & Ruby.
I'd be glad to get some help :)
Thanks in advance!

**Comment by Jarred-Sumner** [comment]
Hi @talhof8,

Could you be a little more specific? More specifically, if you could paste the contents of `heroku logs` that would help me diagnose the problem.

**Comment by talhof8** [comment]
I finally managed to install this. I reinstalled RVM and the other stuff and it worked.
Thanks for time and dedication!
Best,
Tal

**Comment by Jarred-Sumner** [comment]
Glad to hear you got it working!
