### ISSUE TITLE
How to create a new page?

### ISSUE THREAD

**Issue by yulau** [apigy/selfstarter#13]
Hi, I would like to create another web page within the selfstarter,  
like Contact Us or FAQ...etc pages, and with the same header, footer.

I tried to put a new html file into the folder:     /app/views/preorder/contactus.html 
then I expect to have a page with the link:      /preorder/contactus.html  
but seems it's not working.
(Sorry, I am not a programmer)

Can you please help and tell me how to create another webpage that look like the checkout page with the header and footer?

Thanks a lot.

**Comment by cullenbmacdonald** [comment]
This isnt how rails applications works. You would need to create a method in some controller that is told to render the new view you created as well as set up the routes.

**Comment by alexshk** [comment]
If you are not a programmer then I suppose it will be better to find one :smile: 

To create page at `/preorder/contactus.html`:
1. Add line `match '/preorder/contactus'      => 'preorder#contactus'` to `config/routes.rb` (anywhere between `Selfstarter::..` and `end`)
2. Create `app/views/preorder/contactus.html.erb` and put your html there.
3. Create empty method at `app/controllers/preorder_controller.rb`:

``` ruby
def contactus
end
```
1. Restart your server.
