### ISSUE TITLE
Does the original copyright need to be included?

### ISSUE THREAD

**Issue by ripper234** [apigy/selfstarter#23]
I see on the bottom of the site I cloned:

© You. Made by the guys at Lockitron. MIT License.

What part of this can be changed?

I'm not an expert on FOSS licenses, but [this](http://www.tldrlegal.com/license/mit-license) tells me that "I must retain the original copyright."

**Comment by rossgoodby** [comment]
I will be out of the office starting  19/12/2012 and will not return until
31/12/2012.

I will respond to your message when I return. However, if your query is
urgent please contact another member of the IT Team on 0152768125, or email
on it.support@cashconverters.net

---

This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com

---

**Comment by ripper234** [comment]
Ping.

**Comment by ariejan** [comment]
You can do whatever the hell you want with the code: 

> The [..] copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

This does _not_ mean you must display it publicly. But if you would release your fork, it should include the original copyright notice.

But, on the other hand, it would be classy to give some credit where it's due.

**Comment by Jarred-Sumner** [comment]
As @ariejan said, you can just keep the copyright notice somewhere in your code -- it doesn't need to be in the footer, or even visible. We'd like to get credit for it, but you really don't have to. Selfstarter is yours to do what you would like with.

Sorry for the delayed response,
Jarred
