### ISSUE TITLE
Looking for IT Partner

### ISSUE THREAD

**Issue by jverteramo** [apigy/selfstarter#28]
A friend sent me the lockitron/selfstarter site and I am thoroughly intrigued. I have been looking into White Label opportunities, but would prefer a lower cost option if possible and this seems to be the answer. However, I am also a bit nervous as my current partner and I are not tech savvy. So as you may have guessed, I would like to start a crowdfunding platform. I am based in NYC and I think bringing on someone who can handle the IT aspect (basically creating the site from something like selfstarter, backend and frontend development, and maintenance). If anyone is interested, please email me at jverteramo@gmail.com 

Thanks, 
Jared

**Comment by Jarred-Sumner** [comment]
Hey Jared,

This section is intended for issues with Selfstarter -- bug reports, feature requests, and people submitting pull requests. That being said, I'll help you out where I can.

I recommend that you pick up some of the technical aspects of Selfstarter. It's a pretty small Ruby on Rails application. There are several great free resources on the web to help you learn Ruby and Ruby on Rails. Here are a few:
- [Rails Tutorial](http://railstutorial.com)
- [Ruby on Rails Guides](http://guides.rubyonrails.org/)
- [Railscasts](http://railscasts.com)

I hope that helps!
Jarred

**Comment by jverteramo** [comment]
Thanks sorry for the confusion

Sent from my iPhone

On Jan 29, 2013, at 6:15 PM, Jarred Sumner notifications@github.com wrote:

Hey Jared,

This section is intended for issues with Selfstarter -- bug reports,
feature requests, and people posting patches. That being said, I'll help
you out where I can.

I recommend that you pick up some of the technical aspects of Selfstarter.
It's a pretty small Ruby on Rails application. There are several great free
resources on the web to help you learn Ruby and Ruby on Rails. Here are a
few:
- Rails Tutorial http://railstutorial.com
- Ruby on Rails Guides http://guides.rubyonrails.org/
- Railscasts http://railscasts.com

I hope that helps!
Jarred

—
Reply to this email directly or view it on
GitHubhttps://github.com/lockitron/selfstarter/issues/28#issuecomment-12864453.

**Comment by iOSXyZ** [comment]
Peep:

http://founderdating.com/
http://angel.co

## 

Osandi
Founder & CEO
323.899.9980

Vinyl Records Social Exchange™
Facebook | Twitter | Pinterest | Angel List | Instagram
