### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by krasin** [apigy/selfstarter#3]
It would be nice to see a LICENSE file on top of the repository tree.

In general, a permissive license like [MIT](http://en.wikipedia.org/wiki/MIT_License) or [New BSD](http://en.wikipedia.org/wiki/BSD_license#3-clause_license_.28.22New_BSD_License.22_or_.22Modified_BSD_License.22.29) is appreciated, but it's completely up to you, as the authors.

The clear license terms will help others to fork the code and contribute to the project with the confidence.

**Comment by Jarred-Sumner** [comment]
I'm sorry we didn't clarify this to begin start with. It's MIT licensed. I added the license in the top of the repository tree (LICENSE is the file).

Thanks for the heads up.
