### ISSUE TITLE
ArgumentError in PreorderController#prefill

### ISSUE THREAD

**Issue by bluekite2000** [apigy/selfstarter#43]
ArgumentError in PreorderController#prefill

wrong number of arguments (3 for 2)
Rails.root: /Users/trang/Downloads/selfstarter

Application Trace | Framework Trace | Full Trace
app/controllers/preorder_controller.rb:29:in `prefill'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"",
 "payment_option"=>"1",
 "email"=>"",
 "preorder"=>"true",
 "quantity"=>"",
 "commit"=>"Checkout"}
Show session dump

Show env dump

Response

Headers:

None

**Comment by Jarred-Sumner** [comment]
Thanks for the bug report.

It's an issue with the version of `amazon_flex_pay` you're running. Run `bundle update amazon_flex_pay` and that should solve it!
