### ISSUE TITLE
UUID in user.rb seems like a migraiton is missing or something is off

### ISSUE THREAD

**Issue by mredding** [apigy/selfstarter#51]
the line where

self.uuid = some_value

is blowing up with the newest change when trying to create a new user. 

Was there a migraiton adding uuid to the user table that is missing from this check in?

I am getting an error, when going to payment processing when it hits this.

I noticed others have removed this code in user.rb to get the application working again.

**Comment by gmaliar** [comment]
UUID belongs to the order.rb model file, it was fixed in the latest merge.
