### ISSUE TITLE
ActionView::Template::Error (Could not find table 'orders'):

### ISSUE THREAD

**Issue by aarcane** [apigy/selfstarter#79]
attempting to do a test deployment in passenger/rails, on apache debian 7 On first loading the home page I get the following errors in production.log on each load.

Processing by PreorderController#index as HTML
  Rendered preorder/homepage/_value_proposition.html.erb (0.1ms)
  Rendered preorder/homepage/_stats.html.erb (4.2ms)
  Rendered preorder/homepage/_show_dont_tell.html.erb (6.9ms)
  Rendered preorder/index.html.erb within layouts/application (9.1ms)
Completed 500 Internal Server Error in 13ms

ActionView::Template::Error (Could not find table 'orders'):
    20:   <div id="backing">
    21:     <ul>
    22:       <li class="stats" id="backers">
    23:         <%= number_with_delimiter Order.backers, :delimiter => "," %>
    24:         <span><%= Settings.primary_stat %></span>
    25:       </li>
    26:       <li class="stats">
  app/models/order.rb:70:in `backers'
  app/views/preorder/homepage/_stats.html.erb:23:in`_app_views_preorder_homepage__stats_html_erb__2073994486629224114_25188540'
  app/views/preorder/homepage/_show_dont_tell.html.erb:3:in `_app_views_preorder_homepage__show_dont_tell_html_erb__3475623890237893136_28590920'
  app/views/preorder/index.html.erb:1:in`_app_views_preorder_index_html_erb__186831979415567911_28930260'

**Comment by Jarred-Sumner** [comment]
Have you tried running migrations? (“bundle exec rake db:migrate RAILS_ENV=production”)

**Comment by aarcane** [comment]
Thank you @Jarred-Sumner, I found out that passenger has a rails env setting that I had to set to development.  It's working now.  I'm closing this issue, but hope it'll save someone else similar issues in the future.

**Comment by aarcane** [comment]
RailsEnv development
