### ISSUE TITLE
Alternate Payment Processors: Bitcoin and Litecoin support

### ISSUE THREAD

**Issue by EskimoBob** [apigy/selfstarter#8]
Can you please add support for Bitcoin and Litecoin. This will eliminate the needs for Paypal, Amazon, VISA, MC and banks.
FreeNode IRC channel #bitcoin-dev (Development and technical) is probably a good source for additional information.

**Comment by Jarred-Sumner** [comment]
I'm going to be a little opinionated here.

I don't believe that using BitCoin as a payment processor adds value to the kinds of projects Selfstarter is intended    for. BitCoin is kind of an experimental currency -- only accepting BitCoin would, in most cases, dramatically reduce the target audience. Alternatively, accepting BitCoin in addition to using Amazon Payments would be confusing (You'd get non-technical people asking, "What's this BitCoin thing?")

That being said, you can always fork this project and add support on your own.
