### ISSUE TITLE
bundle install --without production

### ISSUE THREAD

**Issue by bigrich** [apigy/selfstarter#84]
When I run 'bundle install --without production' I get an error with the atomic gem.  So I run 'gem install atomic' and it says I need build tools and refers me to devkit, but I have devkit and have reinstalled devkit.  Stuck.

**Comment by Jarred-Sumner** [comment]
I don't have time to look at this closely right now, but I would google something like "install atomic gem windows devkit" and see if there's already a Stackoverflow post. If you find the solution, I'd appreciate it if you could post it here!

I'll take a look a little later today if this isn't already solved by then.

**Comment by bigrich** [comment]
Fixed it, had to reinstall the environment.

**Comment by Jarred-Sumner** [comment]
Thanks for posing that here. Does that mean you reinstalled Ruby via http://rubyinstaller.org/?

**Comment by bigrich** [comment]
yeah, started from scratch

**Comment by Jarred-Sumner** [comment]
Thanks for clarifying.
