### ISSUE TITLE
undefined method `environment'

### ISSUE THREAD

**Issue by jarkelen** [apigy/selfstarter#86]
When setting up the app and running it for the first time, I receive an `undefined method `environment' for nil:NilClass` error. When I disable all imports from `main.css.scss` the site works fine, although without any styling. Any idea what is going wrong?

**Comment by jarkelen** [comment]
I "solved" it by adding all css from all css files into one big main.css.scss file, but still not sure what caused the error, because "environment" is not being used in the stylesheets.

**Comment by Jarred-Sumner** [comment]
This sounds like an issue with initializing Rails during asset precompilation. Try running `bundle exec rake assets:precompile RAILS_ENV=development`. Some things aren't loaded in the `assets` `RAILS_ENV`
