### ISSUE TITLE
Quantity option

### ISSUE THREAD

**Issue by yulau** [apigy/selfstarter#9]
Hi, Thanks for sharing this great source.

I would like to have the "quantity" option in checkout page for people to select/input the number of products they want to buy, like your Lockitron checkout page for people to select.

Right now, the checkout page only have the email field and checkout button, 
Can you please help and tell me how to add this "quantity" function to the site?
and i hope it can trigger the dollars counting on the homepage too, is it possible?

THANKS A LOT.
yu

**Comment by alexshk** [comment]
@yulau, quantity field already present in from, but it is hidden `app/views/preorder/checkout.html.erb`:

```
<%= hidden_field_tag "quantity", params[:quantity] %>
```

you just need to make it as `<input type="text">`:

```
<%= text_field_tag "quantity", params[:quantity] %>
```

and apply some styling to it.

**Comment by yulau** [comment]
Oh, I see, Thank you so much!!!
