### ISSUE TITLE
selfstarter.us website down "Application Error"

### ISSUE THREAD

**Issue by filmathens** [apigy/selfstarter#92]
Selfstarter seems like just what we're looking for but when you go to http://selfstarter.us/ the site is down -- page says:

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your logs for detail

Does not build a lot of confidence. Any fix or other options?

**Comment by pgerhardt** [comment]
Was hosted on Heroku who changed their DNS settings around this time. We updated it to conform to their new DNS policy.

Specifically naked domains no longer work by pointing to one of their three static IP's.
